### ISSUE TITLE
Julia 0.6 support issue tracker

### ISSUE THREAD

**Issue by tkoolen** [tkoolen/RigidBodyDynamics.jl#203]
- [x] https://github.com/JuliaLang/julia/issues/21243
- [x] https://github.com/JuliaLang/julia/issues/21244 / https://github.com/JuliaArrays/StaticArrays.jl/pull/139
- [ ] https://github.com/JuliaLang/julia/issues/21332 (could work around)
- [x] https://github.com/FugroRoames/Rotations.jl/pull/25
- [x] StaticArrays tag: https://github.com/JuliaArrays/StaticArrays.jl/issues/142
- [x] Rotations tag based on StaticArrays tag
- [x] https://github.com/JuliaLang/julia/issues/21410
