### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by tkoolen** [tkoolen/RigidBodyDynamics.jl#282]
- [x] https://github.com/tkoolen/RigidBodyDynamics.jl/issues/280
- [x] StaticArrays tag (https://github.com/JuliaArrays/StaticArrays.jl/issues/276)
- [x] update benchmark results
- [x] add more stuff to README.md
- [x] run tests of previous version on master to catch missing deprecation warnings
- [x] consider adding error for `geometric_jacobian!` change (compact to full)
- [x] news
- [x] release notes

**Comment by tkoolen** [comment]
Release notes:

Highlights:
* drop Julia 0.5 support
* [significant performance improvements](https://github.com/tkoolen/RigidBodyDynamics.jl/commit/52e2ff09eece55164bc3cd9f5b5621d6dc6120be#diff-08b18b9665152647d40df930ab2798a2). The biggest improvements are due to the introduction of `TypeSortedCollection` (#237, #247, #269) and due to the elision of unnecessary cache-staleness checks (#253, #254).
* remove fixed-maximum size matrix code (StaticArrays/Base type piracy)
* get rid of `<:Number` requirement for all types, mainly to support `JuMP` variable/expression types (#276).
* add support for user-defined joint types (as opposed to `QuaternionFloating`, `Revolute`, `Prismatic`, and `Fixed` as the only supported types) (#247)

Notable deprecations and breaking changes:
* `geometric_jacobian[!]` now returns/expects a `GeometricJacobian` with a number of columns that is equal to the number of velocities of the state, instead of the number of velocities of the kinematic path from the base to the body (#269)
* `DynamicsResult` type parameters have changed order, to be more consistent with `MechanismState`. New constructor syntax for `MechanismState` and `DynamicsResult`. Deprecation warnings should help you transition to the new syntax. (#248)
* `Joint`s are now parameterized on their `JointType` to allow joint-type-specific dispatch without resorting to [`@rtti_dispatch`] (#247)(https://github.com/tkoolen/RigidBodyDynamics.jl/issues/209). The old `Joint{T}` is now equivalent to `GenericJoint{T}`, an exported type alias. Note that methods called on `GenericJoint`s will generally allocate due to dynamic dispatch.
* `MechanismState` is now additionally parameterized on the type of its `TypeSortedCollection` of `Joint`s, to allow static dispatch based on joint types. (#247, #258)
